import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import cryptoed from "../public/cryptoed.png";
import youtube from "../public/youtube.png";
import notesapp from "../public/notesapp.png";
import bank from "../public/bank.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React Portfolio-I</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white dark:bg-gray-900 w-full h-full">
        <section className="min-h-screen px-8">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl sm:mr-5">developedbySwap</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl sm:ml-5"
                />
              </li>
              <li>
                <a href='https://drive.google.com/file/d/1GQ0mXKktlrTOuyezOy_Aqc_B4d-dRaCv/view?usp=sharing' download target="blank" className="bg-gradient-to-r from-teal-400 text- to-purple-500 text-white px-4 py-2 border-none rounded-md ml-6">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-10">
            <h2 className="text-5xl py-2 px-2 text-teal-600 font-medium dark:text-teal-400">
              Swapnil Aichbhaumik
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front-End Web Developer
            </h3>
            <p className="text-sm py-5  leading-8 text-gray-800 dark:text-gray-200 mx-auto md:text-xl">
              Freelancer providing services for website design and development.<br/>
               Find more about me from below:
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/Swap-nil-2003" target="blank"><AiFillGithub /></a>
              <a href="https://www.linkedin.com/in/swapnil-aichbhaumik-28a980224/" target="blank"><AiFillLinkedin /></a>
              <a href="https://www.youtube.com/@freecodecamp" target="blank"><AiFillYoutube /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="px-8">
          <div>
            <h2 className="text-4xl py-1 font-bold text-teal-600 dark:text-white ">Services I offer</h2>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer, I've done remote work for
              <span className="text-teal-500"> TheCyberDelta</span> to build their CMS and helped out with the UI/UX of website.
              I have also collaborated with talented people on various projects for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including website designing,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-300 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-bold  pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-300 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-bold  pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools I Use</h4>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">TailwindCSS</p>
              <p className="text-gray-800 py-1">NextJS</p>
              <p className="text-gray-800 py-1">Material UI</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-300 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 ">Teaching</h3>
              <p className="py-2">
                Are you interested in expanding your knowledge about latest technologies? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Learn about</h4>
              <p className="text-gray-800 py-1">Blockchain Development</p>
              <p className="text-gray-800 py-1">Designing</p>
              <p className="text-gray-800 py-1">Web Development</p>
              <p className="text-gray-800 py-1">Coding</p>
            </div>
          </div>
        </section>
        <section className="py-10 px-8">
          <div>
            <h2 className="text-4xl py-1 font-bold text-teal-600 dark:text-white ">Projects</h2>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            <a href="https://crypto-ed-cryptotracking.netlify.app/" target="blank"><Image
                className="object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cryptoed}/><span className="text-teal-600 font-semibold text-xl">Crypto'ed - Crypto and Exchanges tracker </span></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://youtube-clone-react-app02.netlify.app/" target="blank"><Image
                className="object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={youtube}/><span className="text-teal-600 font-semibold text-xl">YouTube2.0</span></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://smart-notezz-app.netlify.app/" target="blank"><Image
                className="object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={notesapp}/><span className="text-teal-600 font-semibold text-xl">SmartNotezz - Notes making App</span></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://modern-business-app.netlify.app/" target="blank"><Image
                className="object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={bank}/><span className="text-teal-600 font-semibold text-xl">Modern Banking Website</span></a>
            </div>
          </div>
        </section>
      </main>
     <footer class="bg-white dark:bg-gray-900">
    <div class="w-full h-full max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
      <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="#" class="hover:underline">Swapnil Aichbhaumik™</a>. All Rights Reserved.
    </span>
    </div>
  </footer>
    </div>
  );
}
